apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: Flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Flaskapp
  template:
    metadata:
      labels:
        app: Flaskapp
    spec:
      containers:
        - name: flaskapp-container
          image: raptor4444/flaskapp2:v1
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
