apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: Flaskapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30004
  type: NodePort
